version: '3.3'
services:
  chrome:
    container_name: chrome
    image: selenium/node-chrome-debug:3.14.0-gallium
    ports:
      - 5900:5900
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    container_name: hub
    image: selenium/hub:3.14.0-gallium
    ports:
      - 4444:4444

  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    ports:
    - 8080:8080
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $HOME/jenkins_data:/var/jenkins_home
